### ISSUE TITLE
Start and end gcode being cover by tooltip window

### ISSUE THREAD

**Issue by TrippJD** [Ghostkeeper/SettingsGuide#105] opened 2022-09-16 12:09 UTC
When editing the start and end gcode inside the printers/machine settings the SettingsGuide window pops up over the entire area blocking your view for editing the code.

![image](https://user-images.githubusercontent.com/46256536/190632389-9495ec1c-5184-4a2f-b183-b2bbcf8adfab.png)

![image](https://user-images.githubusercontent.com/46256536/190632453-a94ed21f-a3f2-4b89-a1da-fda4912988f7.png)

This makes things like selecting a line of text to copy and paste with your mouse quite difficult. Also, for people who subconsciously read text while following along with their mouse pointer it can be frustrating. 

I am guessing that placing the tooltip window outside of the settings window wasn't an option? Because all of the other settings in this window have the same issue but they are not lines of text to edit so its not so bad for them.

Not sure what the best fix is for this. Maybe putting the tooltip a bit higher and adding in a scroll function, or placing the tooltip outside the window.

SettingGuide v2.9.0
cure v5.1.0
Windows 10 v10.0.19044

Thanks for an amazingly useful product. Your work is appreciated!

**Comment by Ghostkeeper** [comment] 2022-09-22 11:23
Duplicate of https://github.com/Ghostkeeper/SettingsGuide/issues/89.

**Closed by Ghostkeeper** 2022-09-22 11:23 UTC
