### ISSUE TITLE
Machine Settings "hints" too large/restricted

### ISSUE THREAD

**Issue by Asterchades** [Ghostkeeper/SettingsGuide#103] opened 2022-09-01 15:12 UTC
The current implementation of the extended "Hints" in the Machine Settings dialogue appear to be restricted to the child window frame. As a result this means that all of the hints provided will at least partially obscure the Start and End GCode sections, while the Marlin Flavour and GCode hints will obscure the entire window. This obstruction requires little more than leaving the mouse cursor in an inopportune location - such as might be done haphazardly when looking for issues in one of the two GCode sections.

The same restriction also means that these dialogues can extend well beyond what is visible, with no means of actually scrolling to see what has been truncated.

I'm unsure as to what a suitable alternative would be. The information is useful, even if only to a specific audience, but the dialogues are simply too large to be confined like that. Their size also means that popping out to the sides - as is the case for print settings - may still not provide enough room, but at least it wouldn't obscure the remainder of the Settings window.

Testing done using Cura 5.1, Settings Guide 2.9.0, under Win11 on a 1920x1080 desktop at 100% scale.

**Comment by Ghostkeeper** [comment] 2022-09-03 17:49
Duplicate of https://github.com/Ghostkeeper/SettingsGuide/issues/89.

**Closed by Ghostkeeper** 2022-09-03 17:49 UTC
