### ISSUE TITLE
Not possible to read or edit start- / stop code

### ISSUE THREAD

**Issue by derrapf** [Ghostkeeper/SettingsGuide#108] opened 2022-10-08 18:20 UTC
Once you try to read or edit the start and/or stop code, you alway get a "Settings-Guide"-Window opened over the the code.
Very annoying.
BR Ralf

**Comment by Ghostkeeper** [comment] 2022-10-09 00:31
Duplicate of #89.

**Closed by Ghostkeeper** 2022-10-09 00:31 UTC
